build: update more
Signed-off-by: AuxXxilium <info@auxxxilium.tech>

diff --git a/.github/workflows/autobuild.yml b/.github/workflows/autobuild.yml
--- a/.github/workflows/autobuild.yml
+++ b/.github/workflows/autobuild.yml
@@ -59,6 +59,56 @@ jobs:
         run: |
           . scripts/func.sh
 
+          function getBuildrootx() {
+            echo "Getting Buildroot-X begin"
+            local DEST_PATH="${1}"
+
+            TAG="$(curl -skLH "Authorization: Bearer ${{ secrets.BUILD_TOKEN }}" https://api.github.com/repos/AuxXxilium/arc-buildroot-x/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')"
+            export BRXTAG="${TAG}"
+            [ ! -d "${DEST_PATH}" ] && mkdir -p "${DEST_PATH}"
+            echo "Getting Kernel"
+            rm -f "${DEST_PATH}/bzImage-arc"
+            if curl -skLH "Authorization: Bearer ${{ secrets.BUILD_TOKEN }}" "https://github.com/AuxXxilium/arc-buildroot-x/releases/download/${TAG}/bzImage" -o "${DEST_PATH}/bzImage-arc"; then
+              echo "Kernel: ${TAG}"
+            else
+              echo "Failed to get Kernel"
+              exit 1
+            fi
+            echo "Getting Ramdisk"
+            rm -f "${DEST_PATH}/initrd-arc"
+            if curl -skLH "Authorization: Bearer ${{ secrets.BUILD_TOKEN }}" "https://github.com/AuxXxilium/arc-buildroot-x/releases/download/${TAG}/rootfs.cpio.xz" -o "${DEST_PATH}/initrd-arc"; then
+              echo "Ramdisk: ${TAG}"
+            else
+              echo "Failed to get Ramdisk"
+              exit 1
+            fi
+          }
+
+          function getBuildroots() {
+            echo "Getting Buildroot-S begin"
+            local DEST_PATH="${1}"
+
+            TAG="$(curl -skLH "Authorization: Bearer ${{ secrets.BUILD_TOKEN }}" https://api.github.com/repos/AuxXxilium/arc-buildroot-s/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')"
+            export BRSTAG="${TAG}"
+            [ ! -d "${DEST_PATH}" ] && mkdir -p "${DEST_PATH}"
+            echo "Getting Kernel"
+            rm -f "${DEST_PATH}/bzImage-arc"
+            if curl -skLH "Authorization: Bearer ${{ secrets.BUILD_TOKEN }}" "https://github.com/AuxXxilium/arc-buildroot-s/releases/download/${TAG}/bzImage" -o "${DEST_PATH}/bzImage-arc"; then
+              echo "Kernel: ${TAG}"
+            else
+              echo "Failed to get Kernel"
+              exit 1
+            fi
+            echo "Getting Ramdisk"
+            rm -f "${DEST_PATH}/initrd-arc"
+            if curl -skLH "Authorization: Bearer ${{ secrets.BUILD_TOKEN }}" "https://github.com/AuxXxilium/arc-buildroot-s/releases/download/${TAG}/rootfs.cpio.xz" -o "${DEST_PATH}/initrd-arc"; then
+              echo "Ramdisk: ${TAG}"
+            else
+              echo "Failed to get Ramdisk"
+              exit 1
+            fi
+          }
+
           echo "Get Dependencies"
           getAddons "files/p3/addons"
           getModules "files/p3/modules"
